"""empty message

Revision ID: 5c589a1f29be
Revises: aabd2b3f4d11
Create Date: 2019-02-20 21:05:07.874107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c589a1f29be'
down_revision = 'aabd2b3f4d11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('OrderDetail',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Order_Index', sa.Integer(), nullable=True),
    sa.Column('Orderer', sa.String(length=64), nullable=True),
    sa.Column('Drink_Size', sa.String(length=64), nullable=True),
    sa.Column('Drink_Item', sa.String(length=64), nullable=True),
    sa.Column('Drink_Ice', sa.String(length=64), nullable=True),
    sa.Column('Drink_Sugar', sa.String(length=64), nullable=True),
    sa.Column('CreateDate', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('OrderList',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('CreateDate', sa.DateTime(), nullable=True),
    sa.Column('Creator', sa.String(length=64), nullable=True),
    sa.Column('DrinkVender', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('OrderList')
    op.drop_table('OrderDetail')
    # ### end Alembic commands ###
