"""empty message

Revision ID: aabd2b3f4d11
Revises: 7adbba857e11
Create Date: 2019-02-10 19:34:45.000056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aabd2b3f4d11'
down_revision = '7adbba857e11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('UserData', sa.Column('DisplayName', sa.String(length=64), nullable=True))
    op.add_column('UserData', sa.Column('PictureURL', sa.String(length=256), nullable=True))
    op.add_column('UserData', sa.Column('StatusMessage', sa.String(length=256), nullable=True))
    op.add_column('UserData', sa.Column('UserID', sa.String(length=64), nullable=True))
    op.drop_column('UserData', 'Description')
    op.drop_column('UserData', 'Name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('UserData', sa.Column('Name', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('UserData', sa.Column('Description', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.drop_column('UserData', 'UserID')
    op.drop_column('UserData', 'StatusMessage')
    op.drop_column('UserData', 'PictureURL')
    op.drop_column('UserData', 'DisplayName')
    # ### end Alembic commands ###
